#include "adc.h"

void ADC_Init(void)
{
//	ADC1_DeInit();

    ADC1->CSR  = ADC1_CSR_RESET_VALUE;
    ADC1->CR1  = ADC1_CR1_RESET_VALUE;
    ADC1->CR2  = ADC1_CR2_RESET_VALUE;
    ADC1->CR3  = ADC1_CR3_RESET_VALUE;
    ADC1->TDRH = ADC1_TDRH_RESET_VALUE;
    ADC1->TDRL = ADC1_TDRL_RESET_VALUE;
    ADC1->HTRH = ADC1_HTRH_RESET_VALUE;
    ADC1->HTRL = ADC1_HTRL_RESET_VALUE;
    ADC1->LTRH = ADC1_LTRH_RESET_VALUE;
    ADC1->LTRL = ADC1_LTRL_RESET_VALUE;
    ADC1->AWCRH = ADC1_AWCRH_RESET_VALUE;
    ADC1->AWCRL = ADC1_AWCRL_RESET_VALUE;

//	ADC1_Init(ADC1_CONVERSIONMODE_CONTINUOUS, ADC1_CHANNEL_2, ADC1_PRESSEL_FCPU_D18,\
//	ADC1_EXTTRIG_TIM, DISABLE, ADC1_ALIGN_RIGHT, ADC1_SCHMITTTRIG_CHANNEL2,DISABLE);

    ADC1->CR2 &= (uint8_t)(~ADC1_CR2_ALIGN);
    ADC1->CR2 |= (uint8_t)(ADC1_ALIGN_RIGHT);
    ADC1->CR1 |= ADC1_CR1_CONT;
    ADC1->CSR &= (uint8_t)(~ADC1_CSR_CH);
    ADC1->CSR |= (uint8_t)(ADC1_CHANNEL_2);
    ADC1->CR1 &= (uint8_t)(~ADC1_CR1_SPSEL);
    ADC1->CR1 |= (uint8_t)(ADC1_PRESSEL_FCPU_D18);
    ADC1->CR2 &= (uint8_t)(~ADC1_CR2_EXTSEL);
    ADC1->CR2 &= (uint8_t)(~ADC1_CR2_EXTTRIG);
    ADC1->CR2 |= (uint8_t)(ADC1_EXTTRIG_TIM);
    ADC1->TDRL |= (uint8_t)((uint8_t)0x01 << (uint8_t)ADC1_SCHMITTTRIG_CHANNEL2);
    ADC1->CR1 |= ADC1_CR1_ADON;


//	ADC1_ITConfig( ADC1_IT_AWS2,ENABLE);
    ADC1->CSR |= (uint8_t)(ADC1_IT_AWS2);

//  ADC1_Cmd(ENABLE);
    ADC1->CR1 |= ADC1_CR1_ADON;

//	ADC1_StartConversion();
    ADC1->CR1 |= ADC1_CR1_ADON;

}
