#ifndef _LED_H_
#define _LED_H_

#include "ht1621.h"
#include "temperature.h"
#include "global_variables.h"

typedef struct _led_seg_t {
    u8		addr;
    u8		val[10];
} led_seg;

#define LED_INDICATOR_PORT		GPIOC
#define LED_INDICATOR_PIN		GPIO_PIN_5

#define LED_INDICATOR_ON        LED_INDICATOR_PORT->ODR |= LED_INDICATOR_PIN
#define LED_INDICATOR_OFF       LED_INDICATOR_PORT->ODR &=~LED_INDICATOR_PIN
#define LED_INDICATOR_TOGGLE    LED_INDICATOR_PORT->ODR ^= LED_INDICATOR_PIN

#define LCD_BACKLIGHT_PORT	    GPIOC
#define LCD_BACKLIGHT_PIN		GPIO_PIN_4

#define LCD_BACKLIGHT_ON        LCD_BACKLIGHT_PORT->ODR |= LCD_BACKLIGHT_PIN
#define LCD_BACKLIGHT_OFF       LCD_BACKLIGHT_PORT->ODR &=~LCD_BACKLIGHT_PIN
#define LCD_BACKLIGHT_TOGGLE    LCD_BACKLIGHT_PORT->ODR ^= LCD_BACKLIGHT_PIN

#define LED_1_DIGITAL_A		(1 << 4)
#define LED_1_DIGITAL_B		(1 << 5)
#define LED_1_DIGITAL_C		(1 << 6)
#define LED_1_DIGITAL_D		(1 << 7)
#define LED_1_DIGITAL_E		(1 << 2)
#define LED_1_DIGITAL_F		(1 << 0)
#define LED_1_DIGITAL_G		(1 << 1)


#define LED_2_DIGITAL_A		(1 << 3)
#define LED_2_DIGITAL_B		(1 << 2)
#define LED_2_DIGITAL_C		(1 << 1)
#define LED_2_DIGITAL_D		(1 << 0)
#define LED_2_DIGITAL_E		(1 << 5)
#define LED_2_DIGITAL_F		(1 << 7)
#define LED_2_DIGITAL_G		(1 << 6)

#define LED1_ADDR	0x02
#define LED2_ADDR	0x04
#define LED3_ADDR	0x06
#define LED4_ADDR	0x08
#define LED5_ADDR	0x0A
#define LED6_ADDR	0x0C
/*
 *     A
 *    ----
 *   |    |
 *  F| G  | B
 *    ----
 *   |    |
 *  E| D  | C
 *    ----  . DP
 */

#define SET_TEMP_1			(1 << 7)

#define LED1_DIGITAL_0		LED_1_DIGITAL_A | LED_1_DIGITAL_B | LED_1_DIGITAL_C | LED_1_DIGITAL_D | LED_1_DIGITAL_E | LED_1_DIGITAL_F |	SET_TEMP_1
#define LED1_DIGITAL_1		LED_1_DIGITAL_B | LED_1_DIGITAL_C | SET_TEMP_1
#define LED1_DIGITAL_2		LED_1_DIGITAL_A | LED_1_DIGITAL_B | LED_1_DIGITAL_D | LED_1_DIGITAL_E | LED_1_DIGITAL_G | SET_TEMP_1
#define LED1_DIGITAL_3		LED_1_DIGITAL_A | LED_1_DIGITAL_B | LED_1_DIGITAL_C | LED_1_DIGITAL_D | LED_1_DIGITAL_G | SET_TEMP_1
#define LED1_DIGITAL_4		LED_1_DIGITAL_B | LED_1_DIGITAL_C | LED_1_DIGITAL_F | LED_1_DIGITAL_G |	SET_TEMP_1
#define LED1_DIGITAL_5		LED_1_DIGITAL_A | LED_1_DIGITAL_C | LED_1_DIGITAL_D | LED_1_DIGITAL_F | LED_1_DIGITAL_G | SET_TEMP_1
#define LED1_DIGITAL_6		LED_1_DIGITAL_A | LED_1_DIGITAL_C | LED_1_DIGITAL_D | LED_1_DIGITAL_E | LED_1_DIGITAL_F | LED_1_DIGITAL_G |	SET_TEMP_1
#define LED1_DIGITAL_7		LED_1_DIGITAL_A | LED_1_DIGITAL_B | LED_1_DIGITAL_C | SET_TEMP_1
#define LED1_DIGITAL_8		LED_1_DIGITAL_A | LED_1_DIGITAL_B | LED_1_DIGITAL_C | LED_1_DIGITAL_D | LED_1_DIGITAL_E | LED_1_DIGITAL_F | LED_1_DIGITAL_G | SET_TEMP_1
#define LED1_DIGITAL_9		LED_1_DIGITAL_A | LED_1_DIGITAL_B | LED_1_DIGITAL_C | LED_1_DIGITAL_D | LED_1_DIGITAL_F | LED_1_DIGITAL_G |	SET_TEMP_1

#define SET_TEMP_2			(1 << 4)

#define LED2_DIGITAL_0		LED_2_DIGITAL_A | LED_2_DIGITAL_B | LED_2_DIGITAL_C | LED_2_DIGITAL_D | LED_2_DIGITAL_E | LED_2_DIGITAL_F |	SET_TEMP_2
#define LED2_DIGITAL_1		LED_2_DIGITAL_B | LED_2_DIGITAL_C | SET_TEMP_2
#define LED2_DIGITAL_2		LED_2_DIGITAL_A | LED_2_DIGITAL_B | LED_2_DIGITAL_D | LED_2_DIGITAL_E | LED_2_DIGITAL_G | SET_TEMP_2
#define LED2_DIGITAL_3		LED_2_DIGITAL_A | LED_2_DIGITAL_B | LED_2_DIGITAL_C | LED_2_DIGITAL_D | LED_2_DIGITAL_G | SET_TEMP_2
#define LED2_DIGITAL_4		LED_2_DIGITAL_B | LED_2_DIGITAL_C | LED_2_DIGITAL_F | LED_2_DIGITAL_G | SET_TEMP_2
#define LED2_DIGITAL_5		LED_2_DIGITAL_A | LED_2_DIGITAL_C | LED_2_DIGITAL_D | LED_2_DIGITAL_F | LED_2_DIGITAL_G | SET_TEMP_2
#define LED2_DIGITAL_6		LED_2_DIGITAL_A | LED_2_DIGITAL_C | LED_2_DIGITAL_D | LED_2_DIGITAL_E | LED_2_DIGITAL_F | LED_2_DIGITAL_G | SET_TEMP_2
#define LED2_DIGITAL_7		LED_2_DIGITAL_A | LED_2_DIGITAL_B | LED_2_DIGITAL_C | SET_TEMP_2
#define LED2_DIGITAL_8		LED_2_DIGITAL_A | LED_2_DIGITAL_B | LED_2_DIGITAL_C | LED_2_DIGITAL_D | LED_2_DIGITAL_E | LED_2_DIGITAL_F | LED_2_DIGITAL_G | SET_TEMP_2
#define LED2_DIGITAL_9		LED_2_DIGITAL_A | LED_2_DIGITAL_B | LED_2_DIGITAL_C | LED_2_DIGITAL_D | LED_2_DIGITAL_F | LED_2_DIGITAL_G | SET_TEMP_2



#define LED1_DIGITAL_0_0		LED_1_DIGITAL_A | LED_1_DIGITAL_B | LED_1_DIGITAL_C | LED_1_DIGITAL_D | LED_1_DIGITAL_E | LED_1_DIGITAL_F
#define LED1_DIGITAL_0_1		LED_1_DIGITAL_B | LED_1_DIGITAL_C
#define LED1_DIGITAL_0_2		LED_1_DIGITAL_A | LED_1_DIGITAL_B | LED_1_DIGITAL_D | LED_1_DIGITAL_E | LED_1_DIGITAL_G
#define LED1_DIGITAL_0_3		LED_1_DIGITAL_A | LED_1_DIGITAL_B | LED_1_DIGITAL_C | LED_1_DIGITAL_D | LED_1_DIGITAL_G
#define LED1_DIGITAL_0_4		LED_1_DIGITAL_B | LED_1_DIGITAL_C | LED_1_DIGITAL_F | LED_1_DIGITAL_G
#define LED1_DIGITAL_0_5		LED_1_DIGITAL_A | LED_1_DIGITAL_C | LED_1_DIGITAL_D | LED_1_DIGITAL_F | LED_1_DIGITAL_G
#define LED1_DIGITAL_0_6		LED_1_DIGITAL_A | LED_1_DIGITAL_C | LED_1_DIGITAL_D | LED_1_DIGITAL_E | LED_1_DIGITAL_F | LED_1_DIGITAL_G
#define LED1_DIGITAL_0_7		LED_1_DIGITAL_A | LED_1_DIGITAL_B | LED_1_DIGITAL_C
#define LED1_DIGITAL_0_8		LED_1_DIGITAL_A | LED_1_DIGITAL_B | LED_1_DIGITAL_C | LED_1_DIGITAL_D | LED_1_DIGITAL_E | LED_1_DIGITAL_F | LED_1_DIGITAL_G
#define LED1_DIGITAL_0_9		LED_1_DIGITAL_A | LED_1_DIGITAL_B | LED_1_DIGITAL_C | LED_1_DIGITAL_D | LED_1_DIGITAL_F | LED_1_DIGITAL_G

#define LED_1_DIGITAL_N			0
#define LED1_DIGITAL_3_0_0		LED_2_DIGITAL_A | LED_2_DIGITAL_B | LED_2_DIGITAL_C | LED_2_DIGITAL_D
#define LED1_DIGITAL_3_0_1		LED_2_DIGITAL_E | LED_2_DIGITAL_F
#define LED1_DIGITAL_3_1_0		LED_2_DIGITAL_B | LED_2_DIGITAL_C
#define LED1_DIGITAL_3_1_1		LED_2_DIGITAL_N
#define LED1_DIGITAL_3_2_0		LED_2_DIGITAL_A | LED_2_DIGITAL_B | LED_2_DIGITAL_D
#define LED1_DIGITAL_3_2_1		LED_2_DIGITAL_E | LED_2_DIGITAL_G
#define LED1_DIGITAL_3_3_0		LED_2_DIGITAL_A | LED_2_DIGITAL_B | LED_2_DIGITAL_C | LED_2_DIGITAL_D
#define LED1_DIGITAL_3_3_1		LED_2_DIGITAL_G
#define LED1_DIGITAL_3_4_0		LED_2_DIGITAL_B | LED_2_DIGITAL_C
#define LED1_DIGITAL_3_4_1		LED_2_DIGITAL_F | LED_2_DIGITAL_G
#define LED1_DIGITAL_3_5_0		LED_2_DIGITAL_A | LED_2_DIGITAL_C | LED_2_DIGITAL_D
#define LED1_DIGITAL_3_5_1		LED_2_DIGITAL_F | LED_2_DIGITAL_G
#define LED1_DIGITAL_3_6_0		LED_2_DIGITAL_A | LED_2_DIGITAL_C | LED_2_DIGITAL_D
#define LED1_DIGITAL_3_6_1		LED_2_DIGITAL_E | LED_2_DIGITAL_F | LED_2_DIGITAL_G
#define LED1_DIGITAL_3_7_0		LED_2_DIGITAL_A | LED_2_DIGITAL_B | LED_2_DIGITAL_C
#define LED1_DIGITAL_3_7_1		LED_2_DIGITAL_N
#define LED1_DIGITAL_3_8_0		LED_2_DIGITAL_A | LED_2_DIGITAL_B | LED_2_DIGITAL_C | LED_2_DIGITAL_D
#define LED1_DIGITAL_3_8_1		LED_2_DIGITAL_E | LED_2_DIGITAL_F | LED_2_DIGITAL_G
#define LED1_DIGITAL_3_9_0		LED_2_DIGITAL_A | LED_2_DIGITAL_B | LED_2_DIGITAL_C | LED_2_DIGITAL_D
#define LED1_DIGITAL_3_9_1		LED_2_DIGITAL_F | LED_2_DIGITAL_G

#define LED_2_DIGITAL_N			0

#define LED1_DIGITAL_4_0_0		LED1_DIGITAL_3_0_0
#define LED1_DIGITAL_4_0_1		LED1_DIGITAL_3_0_1
#define LED1_DIGITAL_4_1_0		LED1_DIGITAL_3_1_0
#define LED1_DIGITAL_4_1_1		LED1_DIGITAL_3_1_1
#define LED1_DIGITAL_4_2_0		LED1_DIGITAL_3_2_0
#define LED1_DIGITAL_4_2_1		LED1_DIGITAL_3_2_1
#define LED1_DIGITAL_4_3_0		LED1_DIGITAL_3_3_0
#define LED1_DIGITAL_4_3_1		LED1_DIGITAL_3_3_1
#define LED1_DIGITAL_4_4_0		LED1_DIGITAL_3_4_0
#define LED1_DIGITAL_4_4_1		LED1_DIGITAL_3_4_1
#define LED1_DIGITAL_4_5_0		LED1_DIGITAL_3_5_0
#define LED1_DIGITAL_4_5_1		LED1_DIGITAL_3_5_1
#define LED1_DIGITAL_4_6_0		LED1_DIGITAL_3_6_0
#define LED1_DIGITAL_4_6_1		LED1_DIGITAL_3_6_1
#define LED1_DIGITAL_4_7_0		LED1_DIGITAL_3_7_0
#define LED1_DIGITAL_4_7_1		LED1_DIGITAL_3_7_1
#define LED1_DIGITAL_4_8_0		LED1_DIGITAL_3_8_0
#define LED1_DIGITAL_4_8_1		LED1_DIGITAL_3_8_1
#define LED1_DIGITAL_4_9_0		LED1_DIGITAL_3_9_0
#define LED1_DIGITAL_4_9_1		LED1_DIGITAL_3_9_1

#define LED_3_DIGITAL_N			0
#define LED_3_DIGITAL_A		(1 << 7)
#define LED_3_DIGITAL_B		(1 << 6)
#define LED_3_DIGITAL_C		(1 << 5)
#define LED_3_DIGITAL_D		(1 << 4)
#define LED1_DIGITAL_5_0_0		LED_3_DIGITAL_A | LED_3_DIGITAL_B | LED_3_DIGITAL_C | LED_3_DIGITAL_D
#define LED1_DIGITAL_5_0_1		LED_2_DIGITAL_E | LED_2_DIGITAL_F
#define LED1_DIGITAL_5_1_0		LED_3_DIGITAL_B | LED_3_DIGITAL_C
#define LED1_DIGITAL_5_1_1		LED_2_DIGITAL_N
#define LED1_DIGITAL_5_2_0		LED_3_DIGITAL_A | LED_3_DIGITAL_B | LED_3_DIGITAL_D
#define LED1_DIGITAL_5_2_1		LED_2_DIGITAL_E | LED_2_DIGITAL_G
#define LED1_DIGITAL_5_3_0		LED_3_DIGITAL_A | LED_3_DIGITAL_B | LED_3_DIGITAL_C | LED_3_DIGITAL_D
#define LED1_DIGITAL_5_3_1		LED_2_DIGITAL_G
#define LED1_DIGITAL_5_4_0		LED_3_DIGITAL_B | LED_3_DIGITAL_C
#define LED1_DIGITAL_5_4_1		LED_2_DIGITAL_F | LED_2_DIGITAL_G
#define LED1_DIGITAL_5_5_0		LED_3_DIGITAL_A | LED_3_DIGITAL_C | LED_3_DIGITAL_D
#define LED1_DIGITAL_5_5_1		LED_2_DIGITAL_F | LED_2_DIGITAL_G
#define LED1_DIGITAL_5_6_0		LED_3_DIGITAL_A | LED_3_DIGITAL_C | LED_3_DIGITAL_D
#define LED1_DIGITAL_5_6_1		LED_2_DIGITAL_E | LED_2_DIGITAL_F | LED_2_DIGITAL_G
#define LED1_DIGITAL_5_7_0		LED_3_DIGITAL_A | LED_3_DIGITAL_B | LED_3_DIGITAL_C
#define LED1_DIGITAL_5_7_1		LED_2_DIGITAL_N
#define LED1_DIGITAL_5_8_0		LED_3_DIGITAL_A | LED_3_DIGITAL_B | LED_3_DIGITAL_C | LED_3_DIGITAL_D
#define LED1_DIGITAL_5_8_1		LED_2_DIGITAL_E | LED_2_DIGITAL_F | LED_2_DIGITAL_G
#define LED1_DIGITAL_5_9_0		LED_3_DIGITAL_A | LED_3_DIGITAL_B | LED_3_DIGITAL_C | LED_3_DIGITAL_D
#define LED1_DIGITAL_5_9_1		LED_2_DIGITAL_F | LED_2_DIGITAL_G


void led_init();
void lcd_clear(void);
void lcd_show(temp_dev	*val);
void lcd_show_setting(btn_setting set_type);
void lcd_show_settings(device_settings *dev_set);

void OpenLCD();
void CloseLCD();


#endif

